language: java
sudo: false

jdk: openjdk11

install: true
script: ./travis.sh

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false
  webhooks:
    - secure: "hYS37V8UTxJrsgR31unzDfv7XLbfdOuWqg0GzoRZzrYMa3TQmD3T6dAKSHJvKXFAD8U42HMWPFHb6c9iIA7jBRmqSJgUxgE4IVQOkZ4//YfgWUG4Awb4aDjqcpLlGxWx+Rw/EzpVLzHJwGguEHbBNRs4reiMP68bH5vTFeLxEVdBdmv8J9bRnhxHs/bddywn6wQcXm0qHAOX0LTBtd58aMGSYGx2qodE4oh5D4gpDtofy/yxrQ1d4e7U5JyhCEvW5pKclKl4XWbMxcnDAdABFtD/mDXLv4HLJEYo6GiViX3BPy3iIqDNNHgbWQgbn7cvxTHj6YLAA7IbMwuUPalmN4/spe1vVSz9pvBhkg9W2qaBgVvORLf7djuYPOADZaemVoB4MNEwsdKUzXNDxiCtT7IAduhGHJy6yr2r+g98nwN55MCA43IAs/3y7TdsGZp/Ra2D+xN4BV9soiTgGUOCQ0GR/RCIROGUg/vi7sTSslS1vUSme+3AQxajX/E2yUHnj0MqoB4BYc/FAhrkgssP3SRqLmC5F6YqtUnQ+PVSbrYd5L/Y2EqocggSx5JzWvNtB2ztEdKj+MypPrAVbiDLzTAuhxv4o7VaRVrVbRnr/nJpq1548AqHFlU9gvn0/ebJtKj9nPwAUoL9auT8iDzKE5lFz7k46D/xEL2H67AaHXk="
